codecov: 
 token: ${{secrets.CODECOV_TOKEN}}
  require_ci_to_pass: true
comment:
  behavior: default
  layout: reach, diff, flags, files, footer
  require_base: false
  require_changes: false
  require_head: true
coverage:
  precision: 2
  range:
  - 70.0
  - 100.0
  round: down
  status:
    changes: false
    patch: true
    project: true
parsers:
  gcov: